### PR TITLE
Allow user to pass any options they want to mailgun.

### PR DESCRIPTION
**Pull request by acinader**
This change will allow a user to send a multipart message or add attachments to a message.

### CODE REVIEW

**Comment by acinader** [comment]
@flovilmart I didn't mean to merge.  fat finger and since we don't have ci setup, it didn't even warn me.  If you have a comment, I'll make a different pr to fix your comment.

Yes, keeping 059a7ef is a good change.  but there are two changes here: 1. i cherry-picked that change which is good but had never been merged. 2. my change.

**Comment by acinader** [comment]
and if its good with you, i'll try and publish to npm.

**Comment by flovilmart** [comment]
I'm afraid any additional options would be merged with the mail payload, and override some values sent by the server. What do you think?

**Comment by acinader** [comment]
I don't think that 'the server' is doing anything with this code.  In the old code, sendMail received an object `mail`.  sendMail would then only put three fields (to, subject, text) into a new `data` object that is then passed to mailgun.  What this change does is allow a client of the adapter to send more than just to, subject and text to mailgun, but any options.  

I don't think that there is any side effect.  The parameter sent into sendMail is not changed, a new Data object is still  created like in the old code, now it is just done with merge.  Another nice thing about this is that you could set the from field on a per message basis.  I could prevent that by changing the order in Object.assign, but I like the way I did it.

**Comment by acinader** [comment]
i think i see what you mean.  you're concern is that on sendMail, the client could potentially overwrite a setting that was used to instantiate the adapter.  

maybe one could over write the domain setting?  I'd need to test it, but if mailgun allows that, then we should support it too.  i think that my change keeps our adapter a very light and allows the client to use mailgun flexibly, so i think it is a good change that lets me do what I need: send multi part with attachements.

**Comment by flovilmart** [comment]
Actually that’s good I misread the code

**Comment by acinader** [comment]
so you ok with it?

I was thinking that I would bump a minor revision and publish.

**Comment by flovilmart** [comment]
Sounds good to me!

**Pull request merged**
