### PR TITLE
Revert "Return after promise rejected."

### PR DESCRIPTION
**Pull request by acinader**
Reverts parse-community/parse-server-simple-mailgun-adapter#2

### CODE REVIEW

**Review by flovilmart — COMMENTED** [review]
Why revert?

**Comment by acinader** [comment]
i didn't mean to merge. doh.
if its ok with you i'll leave it.

**Comment by flovilmart** [comment]
We need to keep it there otherwise reject and resolve may be called in error

**Comment by acinader** [comment]
yes, agreed.  see my comment: https://github.com/parse-community/parse-server-simple-mailgun-adapter/pull/26

**Pull request closed without merging**
