### PR TITLE
Email templates

### PR DESCRIPTION
**Pull request by bcomeau**
## Add configuration for
- Verification email subject
- Verification email body
- Password reset email subject
- Password reset email body
## These variables can be used in the templates
- `%username%` the user's display name
- `%email%` the user's email address
- `%appname%` your application's display name
- `%link%` the link the user must click to perform the requested action
## Example

```
var server = ParseServer({
  ...
  emailAdapter: {
    module: 'parse-server-simple-mailgun-adapter',
    options: {
      // The address that your emails come from
      fromAddress: 'no-reply@yourdomain.com',
      // Your domain from mailgun.com
      domain: 'mg.yourdomain.com',
      // Your API key from mailgun.com
      apiKey: 'key-0123456789abcdefghijklmnopqrstuv',
      // Verification email subject
      verificationSubject: 'Please verify your e-mail for %appname%',
      // Verification email body
      verificationBody: 'Hi,\n\nYou are being asked to confirm the e-mail address %email% with %appname%\n\nClick here to confirm it:\n%link%',
      // Password reset email subject
      passwordResetSubject: 'Password Reset Request for %appname%',
      // Password reset email body
      passwordResetBody: 'Hi,\n\nYou requested a password reset for %appname%.\n\nClick here to reset it:\n%link%'
    }
  }
  ...
});
```

### CODE REVIEW

**Comment by cherukumilli** [comment]
@drew-gross 
This is a pretty good feature.
Can you please review this pull request and help merge it?

**Comment by lucianosimo** [comment]
Hi guys, anyone knows if there is any updates related to this PR? I consider this really useful
Thanks

**Comment by drew-gross** [comment]
A big part of our strategy with adapters in general, and especially email adapters is that we want to keep the "official" ones very simple, then the community can create more complex ones with fancier features. With that in mind, I'd suggest forking this repo, adding your changes, then uploading to `npm` as a new package. Then, we can link to it from here, and from the main Parse Server repo+docs. @cherukumilli @lucianosimo you are of course able to do this as well with these very same changes thanks to the power of open source if @bcomeau doesn't want to!

**Comment by bcomeau** [comment]
It's on npm, https://www.npmjs.com/package/parse-server-mailgun-adapter-template

**Comment by drew-gross** [comment]
Thanks! I'll close this PR, if you want us to add a link to your package and/or GH repo, please use a new PR.

**Pull request closed without merging**
